### ISSUE TITLE
Unexpected state reached when data file not found

### ISSUE THREAD

**Issue by arosien** [jw3/example-daffodil-debug#33]
Using release `0.0.5` via debugger extension:

```
[io-compute-4] INFO  d.d.d.DAPodil - waiting at tcp://0.0.0.0:4711 
[io-compute-4] INFO  d.d.d.DAPodil - connected at tcp://0.0.0.0:4711 
[io-compute-5] DEBUG d.d.d.DAPodil - R> #1 initialize {"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"dfdl","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us","supportsProgressReporting":true,"supportsInvalidatedEvent":true} 
[io-compute-5] DEBUG d.d.d.DAPSession - <R #1 initialize 
[io-compute-5] DEBUG d.d.d.DAPSession - <E initialized 
[io-compute-5] DEBUG d.d.d.DAPodil - R> #2 launch {"type":"dfdl","request":"launch","name":"Debug JPEG","program":"/Users/arosien/nteligen/example-daffodil-debug/jpeg.dfdl.xsd","data":"/Users/arosien/nteligen/example-daffodil-debug/works.jpg","stopOnEntry":true,"trace":false,"debugServer":4711,"__configurationTarget":5,"__sessionId":"e3283f28-fab1-4953-85b0-0ec0a58c9272"} 
Jun 01, 2021 11:23:50 AM com.microsoft.java.debug.core.protocol.AbstractProtocolServer lambda$new$0
SEVERE: Dispatch debug protocol error: java.io.FileNotFoundException: /Users/arosien/nteligen/example-daffodil-debug/works.jpg (No such file or directory)
java.io.FileNotFoundException: /Users/arosien/nteligen/example-daffodil-debug/works.jpg (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at ddb.debugger.dapodil.DAPodil$.$anonfun$run$12(DAPodil.scala:278)
        at cats.effect.IOFiber.blockingR(IOFiber.scala:1145)
        at cats.effect.IOFiber.run(IOFiber.scala:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

[io-compute-1] DEBUG d.d.d.DAPodil - R> #3 setBreakpoints {"source":{"name":"compiler.scala","path":"/Users/arosien/nteligen/example-daffodil-debug/src/main/scala/ddb/debugger/z/compiler.scala"},"lines":[26,28],"breakpoints":[{"line":26},{"line":28}],"sourceModified":false} 
Jun 01, 2021 11:23:50 AM com.microsoft.java.debug.core.protocol.AbstractProtocolServer lambda$new$0
SEVERE: Dispatch debug protocol error: ddb.debugger.dapodil.DAPodil$InvalidState: expected state Launched, was Initialized when receiving request com.microsoft.java.debug.core.protocol.Messages$Request@3d12b395
ddb.debugger.dapodil.DAPodil$InvalidState: expected state Launched, was Initialized when receiving request com.microsoft.java.debug.core.protocol.Messages$Request@3d12b395
        at ddb.debugger.dapodil.DAPodil$InvalidState$.raise(DAPodil.scala:441)
        at ddb.debugger.dapodil.DAPodil.$anonfun$setBreakpoints$1(DAPodil.scala:156)
        at cats.effect.IOFiber.runLoop(IOFiber.scala:383)
        at cats.effect.IOFiber.execR(IOFiber.scala:1126)
        at cats.effect.IOFiber.run(IOFiber.scala:125)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:306)
```

**Comment by arosien** [comment]
Properly logged in b3f7d86.
